# Generated by Django 5.0.3 on 2024-03-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name_plural': 'Notes'},
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='username',
            new_name='user',
        ),
    ]
